### ISSUE TITLE
Non existing route "admin::show-contacts"

### ISSUE THREAD

**Issue by webfactorybulgaria** [TypiCMS/Contacts#5]
In views/mail/message-to-webmaster.blade.php route admin::show-contacts doesn't exist
(we changed it to edit as a quick fix)

**Comment by sdebacker** [comment]
Fixed ! Thanks for reporting.

**Comment by sdebacker** [comment]
Master is currently in a non-stable state because of some big changes I'm doing. Current stable branch is 2.7, I'm publishing this branch for every modules.

**Comment by webfactorybulgaria** [comment]
Thanks let me know when it is back to a stable state.
